# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gameboard.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0004_account_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('solver_count', models.PositiveSmallIntegerField(default=0, null=True)),
                ('point', models.PositiveSmallIntegerField(default=1)),
                ('answer', models.CharField(max_length=32)),
                ('problem_file', models.FileField(upload_to=gameboard.models.get_upload_file_name)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameboard.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='LogEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
            ],
        ),
        migrations.CreateModel(
            name='SolverListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('problem_id', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='entries',
            name='solver_list',
            field=models.ManyToManyField(to='gameboard.SolverListModel'),
        ),
    ]
